(()=>{
 const margin=1.05;
 const money=value=>Number(value).toLocaleString('en-US',{minimumFractionDigits:Number(value)%1?2:0,maximumFractionDigits:2});
 const services=[
  {key:'openai',name:'OpenAI Official Credits',brand:'OpenAI',desc:'Flexible usage credit top-up assistance for eligible OpenAI accounts.',options:[['100','2,500 Credits · Official $100','2,500 Credits — $100 official'],['200','5,000 Credits · Official $200','5,000 Credits — $200 official'],['1000','25,000 Credits · Official $1,000','25,000 Credits — $1,000 official']]},
  {key:'claude',name:'Claude API Credits',brand:'Anthropic Claude',desc:'Prepaid Anthropic API credit top-up assistance for eligible organizations.',options:[20,50,100,200,500,1000].map(v=>[String(v),`$${money(v)} Claude API Credit`,`$${money(v)} credit`])},
  {key:'gemini',name:'Gemini API Credits',brand:'Google Gemini',desc:'Official Google Gemini API prepaid credit top-up assistance.',options:[5,20,50,100,200,500,1000,5000].map(v=>[String(v),`$${money(v)} Gemini API Credit`,`$${money(v)} credit`])}
 ];
 function card(service){
  const options=service.options.map(([value,official,label])=>`<option value="${value}" data-official="${official}">${label}</option>`).join('');
  const first=service.options[0],price=Number(first[0])*margin;
  return `<article class="account-product panel credit-card credit-${service.key}" data-credit-card data-credit-name="${service.name}"><div class="credit-cover"><span class="credit-badge">OFFICIAL</span><div class="credit-logo">${service.key==='gemini'?'✦':service.key==='openai'?'◎':'AI'}</div><span class="credit-brand">${service.brand}</span><strong>${service.name}</strong></div><span class="product-tag">AI Credits</span><h3>${service.name}</h3><p>${service.desc}</p><label class="credit-field"><span>Choose credit amount</span><select data-credit-select>${options}</select></label><div class="official-price">Official amount: <b data-credit-official>${first[1]}</b></div><div class="credit-price-row"><div><small>EVA price</small><div class="credit-price" data-credit-price>$${money(price)} <em>USDT</em></div></div><span class="credit-profit">+5% margin</span></div><div class="stock-line"><span class="in-stock">Available</span><span>Manual top-up</span></div><a class="button primary" data-credit-order target="_blank" rel="noopener noreferrer">Order Selected Credit</a></article>`;
 }
 function update(card){const select=card.querySelector('[data-credit-select]'),opt=select.selectedOptions[0],base=Number(opt.value),sell=Number((base*margin).toFixed(2)),official=opt.dataset.official;card.querySelector('[data-credit-official]').textContent=official;card.querySelector('[data-credit-price]').innerHTML=`$${money(sell)} <em>USDT</em>`;const msg=`Hello, I want ${card.dataset.creditName}. Selected official amount: ${official}. EVA price with 5% service margin: $${money(sell)} USDT. Please help me complete the top-up.`;card.querySelector('[data-credit-order]').href='https://t.me/eva007_8?text='+encodeURIComponent(msg)}
 function mount(){const host=document.getElementById('dashboard-store-products');if(!host||host.dataset.creditsMounted==='1'||host.querySelector('.store-loading'))return false;host.insertAdjacentHTML('beforeend',services.map(card).join(''));host.querySelectorAll('[data-credit-card]').forEach(c=>{c.querySelector('[data-credit-select]').addEventListener('change',()=>update(c));update(c)});host.dataset.creditsMounted='1';return true}
 const timer=setInterval(()=>{if(mount())clearInterval(timer)},250);setTimeout(()=>clearInterval(timer),12000);
})();