(()=>{
  'use strict';
  const scopeSelector='#public-store-products, #official-credits, #dashboard-store-products';
  const cardSelector='.account-product, .product-card, .store-product, [data-credit-card]';
  const state={gyro:false,beta:0,gamma:0,pending:null,cards:new Map()};
  const maxTilt=18;
  const clean=value=>String(value||'').replace(/\s+/g,' ').trim();
  const hash=value=>{let h=2166136261;for(const c of String(value))h=Math.imul(h^c.charCodeAt(0),16777619);return('00000000'+(h>>>0).toString(16)).slice(-8)};
  const productData=card=>{
    const name=clean(card.querySelector('h3')?.textContent||card.dataset.creditName||'EVA Digital Product');
    const category=clean(card.querySelector('.product-tag')?.textContent||'Digital Service');
    const rawDescription=clean(card.querySelector('p')?.textContent);const description=rawDescription||(/aws|azure|cloud|h100|gpu/i.test(name+' '+category)?'Dedicated enterprise cloud quota with secure account access and multi-region availability.':'Verified digital service with secure private delivery.');
    const price=clean(card.querySelector('.product-price,.credit-price,.price')?.textContent||[...card.querySelectorAll('strong')].map(x=>clean(x.textContent)).find(x=>/\$|USDT|QUOTE/i.test(x))||'Contact for price');
    const stock=clean(card.querySelector('.stock-line')?.textContent||'Availability verified before order');
    const cpu=(name+' '+description).match(/(\d{1,4})\s*(?:v?cpu|cores?)/i)?.[1];
    const cloud=/aws|azure|cloud|h100|gpu/i.test(name+' '+category);
    return {name,category,description,price,stock,cpu,cloud};
  };
  const specs=data=>[
    [data.cloud?'Compute allocation':'Plan configuration',data.cpu?`${data.cpu} vCPU allocation`:data.category],
    ['Availability',data.stock||'Verified before order'],
    ['Access & delivery',data.cloud?'Private account dashboard / assisted delivery':'Secure authenticated dashboard delivery'],
    ['Verification','EVA inventory and order audit enabled']
  ];
  const themeFor=data=>/aws/i.test(data.name+' '+data.category)?'aws':/claude/i.test(data.name)?'claude':/gemini|google/i.test(data.name)?'gemini':/chatgpt|openai|gpt/i.test(data.name)?'openai':/telegram/i.test(data.name)?'telegram':'generic';
  const logoFor=data=>{const theme=themeFor(data);return theme==='aws'?'AWS':theme==='claude'?'C':theme==='gemini'?'G':theme==='openai'?'AI':theme==='telegram'?'TG':'EVA'};
  function flip(card,on){card.classList.toggle('eva-is-flipped',on);card.setAttribute('aria-expanded',String(on))}
  function setTiltTarget(card,x,y){const physics=state.cards.get(card);if(!physics)return;physics.targetX=Math.max(-maxTilt,Math.min(maxTilt,x));physics.targetY=Math.max(-maxTilt,Math.min(maxTilt,y))}
  function animateTilt(){state.cards.forEach((physics,card)=>{physics.x+=(physics.targetX-physics.x)*.09;physics.y+=(physics.targetY-physics.y)*.09;card.style.setProperty('--eva-rx',`${physics.x.toFixed(2)}deg`);card.style.setProperty('--eva-ry',`${physics.y.toFixed(2)}deg`)});requestAnimationFrame(animateTilt)}
  function upgrade(card){
    if(card.dataset.evaDimensionReady||!card.closest(scopeSelector))return;
    card.dataset.evaDimensionReady='1';card.classList.add('eva-dimension-card');card.setAttribute('aria-expanded','false');
    const data=productData(card),children=[...card.childNodes],cardPosition=Math.max(0,[...card.parentElement.children].indexOf(card)),serial=clean(card.querySelector('.product-serial')?.textContent)||String(cardPosition+1).padStart(2,'0');
    const inner=document.createElement('div');inner.className='eva-card-inner';
    const front=document.createElement('div');front.className='eva-card-face eva-card-front';
    const label=document.createElement('div');label.className='eva-live-label';label.innerHTML='<span>DimensionCard · 3D Live Tilt</span><i></i>';front.append(label,...children);
    const sheen=document.createElement('div');sheen.className='eva-card-sheen';front.prepend(sheen);
    const head=document.createElement('div');head.className='eva-product-head';head.innerHTML=`<span class="eva-product-number">${escapeHtml(serial)}</span><span class="eva-product-delivery">${/contact|quote/i.test(data.price)?'Assisted Delivery':'Instant Delivery'}</span><span class="eva-product-logo theme-${themeFor(data)}"><span>${logoFor(data)}</span></span>`;front.insertBefore(head,front.querySelector(':scope > .product-tag,:scope > .credit-cover')||front.children[1]||null);
    const priceNode=front.querySelector(':scope > .product-price,:scope > .credit-price-row,:scope > strong');if(priceNode){if(!front.querySelector(':scope > p')){const description=document.createElement('p');description.textContent=data.description;priceNode.before(description)}const priceWrap=document.createElement('div');priceWrap.className='eva-price-display';priceNode.before(priceWrap);priceWrap.append(priceNode);const badge=document.createElement('span');badge.className='eva-pay-badge';badge.innerHTML='-15%<br>EVA PAY';priceWrap.append(badge)}
    const preview=document.createElement('div');preview.className='eva-spec-preview';preview.innerHTML=`<div><span class="eva-spec-icon">▣</span><small>Limit</small><strong>${escapeHtml(data.cpu?`${data.cpu} All Regions`:data.category)}</strong></div><div><span class="eva-spec-icon">♢</span><small>Tier</small><strong>EVA Verified</strong></div>`;const stockNode=front.querySelector(':scope > .stock-line');if(stockNode)stockNode.before(preview);
    const trigger=document.createElement('button');trigger.type='button';trigger.className='eva-flip-trigger';trigger.textContent='Tap or click to see architecture specs';front.append(trigger);
    const back=document.createElement('div');back.className='eva-card-face eva-card-back';
    const fallback=`0x${hash(data.name)}${hash(data.category)}${hash(data.price)}${hash(data.name+data.stock)}`;
    back.innerHTML=`<div class="eva-back-kicker"><span>Architecture Blueprint</span><b>Technical Verification</b></div><h3>${escapeHtml(data.name)}</h3><p>${escapeHtml(data.description)}</p><div class="eva-spec-list">${specs(data).map(([a,b])=>`<div class="eva-spec"><small>${escapeHtml(a)}</small><strong>${escapeHtml(b)}</strong></div>`).join('')}</div><div class="eva-audit"><small>Cryptographic Card Hash</small><code>${fallback}</code></div><button class="eva-gyro-button" type="button" aria-pressed="false">Enable Device Gyroscope for Motion Tilt</button><button class="eva-flip-trigger eva-return" type="button">Return to Product View</button>`;
    inner.append(front,back);card.append(inner);
    if(window.crypto?.subtle){window.crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${data.name}|${data.category}|${data.price}|${data.stock}`)).then(buffer=>{back.querySelector('.eva-audit code').textContent='0x'+[...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,'0')).join('')}).catch(()=>{})}
    trigger.addEventListener('click',()=>flip(card,true));back.querySelector('.eva-return').addEventListener('click',()=>flip(card,false));
    back.querySelector('.eva-gyro-button').addEventListener('click',event=>enableGyro(event.currentTarget));
    state.cards.set(card,{x:0,y:0,targetX:0,targetY:0,dragging:false,startX:0,startY:0});
    card.addEventListener('pointerdown',event=>{const physics=state.cards.get(card);physics.dragging=event.pointerType==='touch'||event.pointerType==='pen';physics.startX=event.clientX;physics.startY=event.clientY;if(physics.dragging)card.setPointerCapture?.(event.pointerId)});
    card.addEventListener('pointermove',event=>{if(state.gyro||card.classList.contains('eva-is-flipped'))return;const r=card.getBoundingClientRect(),physics=state.cards.get(card);let x,y;if(physics.dragging){x=(event.clientX-physics.startX)/10;y=(event.clientY-physics.startY)/10;setTiltTarget(card,-y,x)}else{if(event.pointerType==='touch')return;x=(event.clientX-r.left)/r.width-.5;y=(event.clientY-r.top)/r.height-.5;setTiltTarget(card,-y*maxTilt,x*maxTilt)}card.style.setProperty('--eva-sheen-x',`${((event.clientX-r.left)/r.width)*100}%`);card.style.setProperty('--eva-sheen-y',`${((event.clientY-r.top)/r.height)*100}%`);card.style.setProperty('--eva-sheen-opacity','.7')});
    const release=()=>{const physics=state.cards.get(card);if(physics)physics.dragging=false;if(!state.gyro)setTiltTarget(card,0,0);card.style.setProperty('--eva-sheen-opacity','0')};
    card.addEventListener('pointerup',release);card.addEventListener('pointercancel',release);card.addEventListener('pointerleave',release);
  }
  const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function scan(root=document){root.querySelectorAll?.(`${scopeSelector} ${cardSelector}`).forEach(upgrade)}
  function onOrientation(event){state.beta=Number(event.beta)||0;state.gamma=Number(event.gamma)||0;document.querySelectorAll('.eva-dimension-card').forEach(card=>{if(!card.classList.contains('eva-is-flipped'))setTiltTarget(card,(45-state.beta)*.7,state.gamma*.7)})}
  async function enableGyro(button){
    try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const result=await DeviceOrientationEvent.requestPermission();if(result!=='granted')throw new Error('Permission not granted')}
      window.addEventListener('deviceorientation',onOrientation,{passive:true});state.gyro=true;document.querySelectorAll('.eva-gyro-button').forEach(b=>{b.setAttribute('aria-pressed','true');b.textContent='Device Gyroscope Enabled'});
    }catch{button.textContent='Gyroscope permission was not enabled'}
  }
  function ensureModal(){
    if(document.querySelector('.eva-balance-modal'))return;
    const modal=document.createElement('div');modal.className='eva-balance-modal';modal.hidden=true;modal.innerHTML=`<div class="eva-balance-scrim" data-eva-cancel></div><section class="eva-balance-panel" role="dialog" aria-modal="true" aria-labelledby="eva-balance-title"><div class="eva-modal-kicker">Secure EVA Checkout</div><h2 id="eva-balance-title">Authorize EVA Balance</h2><p>Instant delivery to your authenticated account dashboard.</p><div class="eva-balance-lines"><span>Asset <b data-eva-asset></b></span><span class="eva-deduction">Deduction <b data-eva-price></b></span><span>EVA Network Fee <b>0.00 USDT (Waived)</b></span></div><div class="eva-balance-actions"><button class="eva-balance-cancel" type="button" data-eva-cancel>Cancel</button><button class="eva-balance-confirm" type="button">Confirm Order</button></div></section>`;document.body.append(modal);
    modal.querySelectorAll('[data-eva-cancel]').forEach(x=>x.addEventListener('click',()=>{modal.hidden=true;state.pending=null}));
    modal.querySelector('.eva-balance-confirm').addEventListener('click',()=>{const pending=state.pending;if(!pending)return;modal.hidden=true;state.pending=null;if(pending.type==='dashboard'){pending.button.dataset.evaAuthorized='1';const old=window.confirm;window.confirm=()=>true;pending.button.click();window.confirm=old}else{sessionStorage.setItem('eva-pending-product',JSON.stringify({name:pending.data.name,price:pending.data.price}));sessionStorage.setItem('eva-return-to','/dashboard.html#customer-products');location.href=pending.href||'/login.html'}});
  }
  function openBalance(card,target,type){ensureModal();const modal=document.querySelector('.eva-balance-modal'),data=productData(card);state.pending=type==='dashboard'?{type,button:target,data}:{type:'public',href:target.getAttribute('href'),data};modal.querySelector('[data-eva-asset]').textContent=data.name;modal.querySelector('[data-eva-price]').textContent=data.price;modal.hidden=false;
  }
  document.addEventListener('click',event=>{const target=event.target.closest('a,button');if(!target)return;const card=target.closest('.eva-dimension-card');if(!card)return;if(target.classList.contains('buy-product')){if(target.dataset.evaAuthorized==='1'){delete target.dataset.evaAuthorized;return}event.preventDefault();event.stopImmediatePropagation();openBalance(card,target,'dashboard');return}if(target.matches('a.button[href*="login.html"]')&&/buy|balance/i.test(target.textContent)){event.preventDefault();event.stopImmediatePropagation();openBalance(card,target,'public')}},true);
  function showSuccess(){ensureModal();const modal=document.querySelector('.eva-balance-modal');modal.innerHTML='<div class="eva-balance-scrim"></div><section class="eva-balance-panel eva-success-copy" role="dialog" aria-modal="true"><div class="eva-success-mark">✓</div><h2>Order Executed Successfully</h2><p>Order created successfully. Delivery details will appear in your secure vault.</p><button type="button">Return to Dashboard</button></section>';modal.hidden=false;modal.querySelector('button').addEventListener('click',()=>{modal.remove();location.hash='customer-orders'})}
  function mountConsole(){const store=document.querySelector('#public-store-products');if(!store||document.querySelector('.eva-dimension-console'))return;const consoleBox=document.createElement('section');consoleBox.className='eva-dimension-console';consoleBox.innerHTML='<div class="eva-console-title"><span class="eva-console-icon">◇</span><span class="eva-console-copy"><strong>DIMENSION <em>CARD</em> 3D <span class="eva-console-live">LIVE TILT</span></strong><small>Interactive Gyro &amp; Physics Tilt Demo</small></span></div><div class="eva-console-tabs"><button class="eva-console-tab active" data-eva-find="aws" type="button">◉ AWS 512</button><button class="eva-console-tab" data-eva-find="azure" type="button">♙ Azure 256</button><button class="eva-console-tab" data-eva-find="h100|gpu" type="button">▣ H100 Pod</button></div><div class="eva-console-actions"><button type="button" data-eva-motion>⌁</button><button type="button" data-eva-reset>↻</button><button class="eva-console-flip" type="button" data-eva-global-flip>▣ &nbsp; Flip Card</button></div>';store.before(consoleBox);const guide=document.createElement('div');guide.className='eva-motion-guide';guide.innerHTML='<span><b>↖</b>Move mouse or drag on touchscreen to rotate in 3D</span><button type="button">Enable Device Gyroscope for Motion Tilt</button>';store.after(guide);consoleBox.querySelector('[data-eva-reset]').addEventListener('click',()=>document.querySelectorAll('.eva-dimension-card').forEach(card=>{flip(card,false);setTiltTarget(card,0,0)}));consoleBox.querySelector('[data-eva-global-flip]').addEventListener('click',()=>{const card=document.querySelector('#public-store-products .eva-dimension-card');if(card)flip(card,!card.classList.contains('eva-is-flipped'))});consoleBox.querySelectorAll('[data-eva-find]').forEach(button=>button.addEventListener('click',()=>{consoleBox.querySelectorAll('.eva-console-tab').forEach(tab=>tab.classList.toggle('active',tab===button));const matcher=new RegExp(button.dataset.evaFind,'i'),card=[...store.querySelectorAll('.eva-dimension-card')].find(item=>matcher.test(productData(item).name+' '+productData(item).category));card?.scrollIntoView({behavior:'smooth',block:'center'})}));consoleBox.querySelector('[data-eva-motion]').addEventListener('click',event=>enableGyro(event.currentTarget));guide.querySelector('button').addEventListener('click',event=>enableGyro(event.currentTarget));}
  const observer=new MutationObserver(records=>{for(const record of records){for(const node of record.addedNodes){if(node.nodeType===1){if(node.matches?.(cardSelector))upgrade(node);scan(node)}}}mountConsole();const notice=document.getElementById('dash-notice');if(notice?.classList.contains('success')&&/purchase successful/i.test(notice.textContent)&&notice.dataset.evaSeen!==notice.textContent){notice.dataset.evaSeen=notice.textContent;showSuccess()}});
  const start=()=>{scan();mountConsole();requestAnimationFrame(animateTilt);observer.observe(document.body,{childList:true,subtree:true,characterData:true})};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();
